#!/usr/bin/env bash
if [ ! "$BASH_SOURCE" = "$0" ] ; then
  echo "ERR: script should only be used directly" >&2
  exit 1
fi

PYBOOK_INIT=$(dirname $0)/__init__.py # ! Must be valid initialization file

python3 $PYBOOK_INIT $@

exit 0