#!/usr/bin/env bash
if [ ! "$BASH_SOURCE" = "$0" ] ; then
  echo "ERR: script should only be used directly" >&2
  exit 1
fi

VENV_PATH=$(dirname $0)/.venv/bin/activate # ! Must be valid python environment
PYBOOK_INIT=$(dirname $0)/__init__.py # ! Must be valid initialization file

. $VENV_PATH
python3 $PYBOOK_INIT $@
deactivate

exit 0